# Generated by Django 5.0 on 2023-12-05 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_stats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_timestamp", models.DateTimeField(auto_now_add=True)),
                ("finish_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "players",
                    models.ManyToManyField(
                        related_name="games", to="game_stats.player"
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game_stats.player",
                    ),
                ),
            ],
        ),
    ]
