# Generated by Django 4.2.8 on 2023-12-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_stats", "0002_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stat",
            name="score",
            field=models.PositiveIntegerField(),
        ),
    ]
