# Generated by Django 4.2.8 on 2023-12-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_stats", "0004_alter_game_players_alter_stat_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="profile_image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
