# Generated by Django 4.2.8 on 2023-12-08 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game_stats", "0005_alter_player_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="finish_timestamp",
        ),
        migrations.RemoveField(
            model_name="game",
            name="start_timestamp",
        ),
        migrations.AddField(
            model_name="stat",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game_stats.game",
            ),
        ),
    ]
